# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 451)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 321, 61))
        self.label_result.setStyleSheet("font: 52pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 219, 120)")
        self.label_result.setObjectName("label_result")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 60, 81, 80))
        self.btn_7.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);\n"
"")
        self.btn_7.setObjectName("btn_7")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(160, 60, 81, 80))
        self.btn_9.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_9.setAutoDefault(False)
        self.btn_9.setObjectName("btn_9")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(80, 60, 81, 80))
        self.btn_8.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_8.setObjectName("btn_8")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(80, 140, 81, 80))
        self.btn_5.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 140, 81, 80))
        self.btn_4.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(160, 140, 81, 80))
        self.btn_6.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_6.setObjectName("btn_6")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(80, 220, 81, 80))
        self.btn_2.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_2.setObjectName("btn_2")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 220, 81, 80))
        self.btn_1.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(160, 220, 81, 80))
        self.btn_3.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_3.setObjectName("btn_3")
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(240, 60, 81, 81))
        self.btn_divide.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(220, 100, 50);")
        self.btn_divide.setAutoDefault(False)
        self.btn_divide.setObjectName("btn_divide")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(240, 140, 81, 81))
        self.btn_mult.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(220, 100, 50);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(240, 220, 81, 81))
        self.btn_minus.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(220, 100, 50);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(240, 300, 81, 151))
        self.btn_plus.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(220, 100, 50);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(0, 380, 241, 71))
        self.btn_equal.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(192, 34, 23);\n"
"")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 300, 241, 80))
        self.btn_zero.setStyleSheet("font: 40pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 214, 192);")
        self.btn_zero.setObjectName("btn_zero")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_divide.setText(_translate("MainWindow", "/"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_zero.setText(_translate("MainWindow", "0"))

    def add_functions(self):
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_mult.clicked.connect(lambda: self.write_number(self.btn_mult.text()))
        self.btn_divide.clicked.connect(lambda: self.write_number(self.btn_divide.text()))

        self.btn_equal.clicked.connect(self.results)

    def write_number(self, number):
        if self.label_result.text() == "0" or self.is_equal:
            self.label_result.setText(number)
            self.is_equal = False
        else:
            self.label_result.setText((self.label_result.text()+number))

    def results(self):
        res = eval(self.label_result.text())
        self.label_result.setText("Результат: " + str(res))
        self.is_equal = True

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
